services:
  app:
    image: app_image
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - "8501"

  nginx:
    image: nginx_image
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - app
